spring:
  application:
    name: exam-system-api

  datasource:
    url: jdbc:postgresql://localhost:5432/edu_onl
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_client_id
            client-secret: your_google_client_secret
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

jwt:
  secret: MyVerySecureSecretKeyThatIsAtLeast256BitsLongForJWTSigningPurposesOnly
  expiration: 86400000